#!/bin/bash
hugo new site dist
cd dist
git clone https://github.com/theNewDynamic/gohugo-theme-ananke.git
mkdir themes/ananke
mv gohugo-theme-ananke/* themes/ananke
echo theme = \"ananke\" >>config.toml
sed -i 's/My New Hugo Site/Awesome Inc./' config.toml
hugo new page/index.html
hugo new post/welcome.md >>public/index.html
hugo -D
